[versions]
core-ktx = "1.9.0"
agp = "7.3.1"
kotlin = "1.6.10"
coil = "1.3.2"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }


